React capstone project
melaniesigrid/studio_ghibli pull request #9
Opened 2022-03-16 21:28 UTC by melaniesigrid

Hello, and thank you for reviewing my project! On this PR...

- Create a single-page application (SPA) built with React and Redux.
- The data retrieved from the API is stored in the Redux store.
- I filter the data that you retrieve from the API using a Filter stateless component, using the useParams() hook to take the id of the card being clicked and filter to give the correct details.
- Every page (the main page and the pages for each item) have a unique route within the SPA.
- The project is deployed.

<img src="https://media4.giphy.com/media/XlRcJ5YV0qQvu/giphy.gif"/>

2022-03-16 22:14 UTC, hiromataba requested changes
Hi @melaniesigrid :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/158700005-d4c7e867-51c4-406d-b8c4-1b5f9bf6bb4b.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
### To highlight :medal_military: 
- Nice design :heavy_check_mark: 
- Your linters are passing :heavy_check_mark: 
- Nice commit history :+1: 
- Professional README file :heavy_check_mark: 

## Required Changes ♻️

- [ ] As this is a mobile web app I think the mobile version should match the provided design please fix your navbar setting and microphone icons style :point_down: 

![image](https://user-images.githubusercontent.com/75126481/158699876-e909bcf1-0f5c-4077-85c1-ea0ac0aaa07f.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 22:48 UTC, melaniesigrid commented on README.md
> -
Thank you very much for your useful suggestions and for reviewing my project! I have implemented the changes. ⭐

2022-03-16 22:58 UTC, MahmoudBakr23 approved these changes
Hi @melaniesigrid 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 23:07 UTC, merged

2022-03-17 09:38 UTC, hiromataba commented on README.md
> -
You are welcome @melaniesigrid :wink: